# Generated by Django 3.1.6 on 2021-02-16 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('take_attendance', '0002_auto_20210216_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='take_attendance',
            name='date',
            field=models.DateField(),
        ),
    ]
